spring:
  freemarker:
    check-template-location: false
  profiles:
    #环境设置
    active: '@spring.profiles.active@'
  application:
    name: '@artifactId@'
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
  #类型别名
  type-aliases-package: com.fu.springbootdemo.entity
  # 扫描通用枚举包，需要配置@EnumValue注解使用
  type-enums-package: com.fu.springbootdemo.enums
  #读取xml
  mapper-locations: classpath:mapper/*.xml