server:
  port: 8180

spring:
  application:
    name: '@artifactId@'
  profiles:
    active: '@spring.profiles.active@'
  mvc:
    contentnegotiation:
      # 开启参数内容协商，一般推荐通过请求头Accept : application/json 或 application/xml，来返回对应格式的内容
      favor-parameter: true
      # 参数名称，默认名称为：format。请求接口在接口后面加上参数?format=xml即可返回xml参数形式的数据。
      parameter-name: format

pig:
  id: '1'
  name: '佩奇'

pig2:
  id: '2'
  name: '佩奇2'
logging:
  level:
    sql: debug
